# production mode
version: '3.5'
services:
  scheduler:
    image: candilib_scheduler:${APP_VERSION:-latest}
    container_name: candilib_scheduler
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        NPM_AUDIT_DRY_RUN: ${NPM_AUDIT_DRY_RUN}
        APP_VERSION: ${APP_VERSION}
#    ports:
#      - "${SCHEDULER_PORT:-8000}:8000"
#    env_file:
#      - ${cnf:-.env}
    environment:
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL:-mongodb://adminCandilib:changeme78@db:27017/candilib}

networks:
  default:
    external:
      name: ${APP}-network
