# production mode
version: '3.5'
services:
  db:
    image: mongo:4.2.7
    container_name: candilib_mongo
    volumes:
      - ${DBDATA:-../mongo}:/data/db
      - ./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "${DB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS:-changeme}
      MONGO_INITDB_DATABASE: ${DB_NAME:-candilib}
      DB_USER: ${DB_USER:-adminCandilib}
      DB_PASS: ${DB_PASS:-changeme78}
networks:
  default:
    external:
      name: ${APP}-network
