version: '3.5'
services:
  db:
    image: mongo:4
    volumes:
      - ../mongo-dev/db:/data/db
      - ./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "${DB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS:-changeme}
      MONGO_INITDB_DATABASE: ${DB_NAME:-candilib}
      DB_USER: ${DB_USER:-adminCandilib}
      DB_PASS: ${DB_PASS:-changeme78}

networks:
  candilib-network:
    name: candilib-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
