# production mode
version: '3.5'
services:
  api:
    image: candilib_api:${APP_VERSION:-latest}
    container_name: candilib_api
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        NPM_AUDIT_DRY_RUN: ${NPM_AUDIT_DRY_RUN}
        APP_VERSION: ${APP_VERSION}
    ports:
      - "${API_PORT:-8000}:8000"
#    env_file:
#      - ${cnf:-.env}
    environment:
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL:-mongodb://adminCandilib:changeme78@db:27017/candilib}
      SMTP_SERVER: ${SMTP_SERVER:-smtp}
      SMTP_PORT: ${SMTP_PORT:-25}
      MAIL_FROM: ${MAIL_FROM:-noreply@interieur.gouv.fr}
      CANDIDAT_EXPIREDIN: ${CANDIDAT_EXPIREDIN:-72h}
      PUBLIC_URL: ${PUBLIC_URL:-http://localhost:8080}
      ADMIN_URL: ${ADMIN_URL:-http://localhost:8080}
      SECRET: ${SECRET}

networks:
  default:
    external:
      name: ${APP}-network
