# development mode
version: '3.4'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - candilib-network
    volumes:
      - mongodata:/data/db
      - ./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS:-changeme}
      MONGO_INITDB_DATABASE: ${DB_NAME:-candilib}
      DB_USER: ${DB_USER:-adminCandilib}
      DB_PASS: ${DB_PASS:-changeme78}

  api:
    image: candilib_api:${APP_VERSION:-latest}
    build:
      target: development
      context: ./
      dockerfile: Dockerfile
      args:
        proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
    volumes:
      - .:/app:delegated
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location. Thanks to PR from @brnluiz
      - notused:/app/node_modules
    container_name: candilib_api
    depends_on:
      - db
      - fakesmtp
    ports:
      - "${WEB_PORT:-8000}:8000"
      - "9229:9229"
#    env_file:
#      - ${cnf:-.env}
    environment:
      NODE_ENV: development
      MONGO_URL: ${MONGO_URL:-mongodb://db:27017/candilib}
      SMTP_SERVER: candilib_smtp
      SMTP_PORT: 25
      MAIL_FROM: noreply@interieur.gouv.fr
      CANDIDAT_EXPIREDIN: 72h
      PUBLIC_URL: http://localhost:8080
      DB_NAME: ${DB_NAME:-candilib}
      DB_USER: ${DB_USER:-adminCandilib}
      DB_PASS: ${DB_PASS:-changeme78}

    networks:
      - candilib-network
  fakesmtp:
    image: digiplant/fake-smtp
    container_name: candilib_smtp
    volumes:
      - ../../output:/var/mail
    ports:
    - "25:2525"
    networks:
      - candilib-network

networks:
  candilib-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
volumes:
  notused:
  mongodata:
